nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

web:
  build: ./web
  links:
    - postgres:postgres
  ports:
    - "5002:5000"
  command: /usr/bin/python /app/app.py
  restart: always
  volumes:
    - ./web:/app
  env_file: .env

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5431:5431"
